### ISSUE TITLE
Theme Switcher

### ISSUE THREAD

**Issue by 1VinceP** [1VinceP/vue-simple-notes#11]
Having a light theme would be nice, but if you want to create multiple different themes, go nuts! Just make sure there is a simple way to change themes

**Comment by astnxavier** [comment]
Hey there, I'd be happy to help out with a light theme toggle for Hacktoberfest

(originally found this issue through http://issuehub.io/)

([PR](https://github.com/1VinceP/vue-simple-notes/pull/26))

**Comment by 1VinceP** [comment]
Sorry, busy day. Sounds good! I just noticed you got a PR up, I'll take a look when I get some time

**Comment by astnxavier** [comment]
I get it, no worries! 

Let me know if there is more that needs updating
