### ISSUE TITLE
Comments!

### ISSUE THREAD

**Issue by 1VinceP** [1VinceP/vue-simple-notes#15]
If you are new to Vue and would like to contribute while learning the ropes, head over to the [Vue docs](https://vuejs.org/) and add comments explaining what everything does!

Example:
```js
// these are functions that can be accessed in other parts of the script or in the template
methods: {...}
```

Please don't work on this issue if you are familiar with Vue.
If your PR includes only the example or a few changes, it will be marked as spam. Please be thorough.

**Comment by rebekris** [comment]
Hi! I want to learn! :)

**Comment by 1VinceP** [comment]
@rebekris Wonderful, I've assigned you to the issue

**Comment by rebekris** [comment]
@1VinceP thanks so much

**Comment by 1VinceP** [comment]
Just to clarify, _this issue_ specifically is reserved for contributors that are new to Vue. The other issues may be taken on by anyone of any experience level.

**Comment by rebekris** [comment]
hi @1VinceP! 
can U check my commit? tell me.

**Comment by 1VinceP** [comment]
@rebekris you will have to make a pull request

**Comment by 1VinceP** [comment]
Sorry, it just popped up for me. Taking a look!
