### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by kamerat** [1VinceP/vue-simple-notes#17]
I stumbled upon your repo while browsing hacktoberfest tags.
There is no readme, so it is hard to understand what this is. To add to the confusion, in #15 you are saying 

>Please don't work on this if you are familiar with Vue. 

Do you mean that task specifically or the whole repo? - Is this some sort of Vue-learning hacktoberfest repo?

I think answering these questions would help more people contribute or move on.

**Comment by 1VinceP** [comment]
Thank you for your comments. I will update the readme.

> Do you mean that task specifically or the whole repo? - Is this some sort of Vue-learning hacktoberfest repo?

For that task specifically. I will update the issue.

**Comment by 1VinceP** [comment]
This was originally created as a project for Hacktober fest with some friends to contribute if they wanted. I honestly wasn't expecting it to garner much interest, but since it is, I am more than happy to make it more accessible for others to make contributions.

**Comment by kamerat** [comment]
Thank you for the quick reply! This answers all my questions 👍
